Fixes #23932 - Fixes failing application job tests for some plugins
The tests were failing with:
Sequel::DatabaseError: PG::DuplicateTable:
ERROR:  relation "dynflow_execution_plans" already exists

This failure was probably caused by forcing initialization of the
Dynflow world in a before test block.