Refs #36815 - explicitly require redis
ActiveSupport only loads the Redis gem when one enables RedisCacheStore,
but we need to obtain the default values before that.

For some reason this did not break on EL, but only on Debian.
Maybe because we use plain gems on the one vs bundler on the other.

Error:

    rake aborted!
    NameError: uninitialized constant Redis
    /usr/share/foreman/config/application.rb:312:in `<class:Application>'
    /usr/share/foreman/config/application.rb:102:in `<module:Foreman>'
    /usr/share/foreman/config/application.rb:101:in `<top (required)>'
    /usr/share/foreman/Rakefile:1:in `require'
    /usr/share/foreman/Rakefile:1:in `<top (required)>'
    /usr/share/foreman/vendor/ruby/2.7.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
    (See full trace by running task with --trace)