Fixes #36201 - Remove window.update_interface_table from vmware.js
The error it triggers is: Uncaught TypeError: window.update_interface_table is not a function

I don't think this ever worked, and everything still seem to work in vmware.
it probably wanted to update the interfaces section on the vmware page when changing clusters,
but the code for that update_interface_table function exists in host_edit_interface.js which is not in the webpack directory
which means we would need to export it from there and move those methods into webpack and assign them under the window.tfm object.