Fixes #38329 - Avoid frozen string modification
When dealing with frozen strings, `<<` breaks. Using `+=` unfreezes the
string and is thus safer.

    [1] pry(main)> msg = 'x'.freeze
    => "x"
    [2] pry(main)> msg.frozen?
    => true
    [3] pry(main)> msg << 'y'
    FrozenError: can't modify frozen String: "x" (FrozenError)
    from (pry):3:in `__pry__'
    [4] pry(main)> msg += 'y'
    => "xy"
    [5] pry(main)> msg.frozen?
    => false