fixes #24046 - return id as str for name as last resort
Foreman HasManyCommon concern uses 'id' as a value of last resort for
the name of an attribute. But Rails expects this value to a return a
string. This causes a problem for Katello. Take a look at the output
here in Katello:

```
irb(main):001:0> Host.first
Hirb Error: undefined method `gsub' for 2:Integer
```

Where's that coming from?

```
<pre>
irb(main):006:0> Host.first.content_facet_attributes.to_s
=> 2
irb(main):007:0> Host.first.content_facet_attributes.to_s.is_a?(String)
=> false
</pre>
```