add back logrotate file
this was removed in 221445d, but logrotate is not part of rpms-spec repo
which result in:
+ install -Dp -m0644 foreman.sysconfig /builddir/build/BUILDROOT/foreman-1.0.1-33.13833d4.fc17.noarch/etc/sysconfig/foreman
+ install -Dp -m0755 foreman.init /builddir/build/BUILDROOT/foreman-1.0.1-33.13833d4.fc17.noarch/etc/rc.d/init.d/foreman
+ install -Dp -m0644 extras/spec/logrotate /builddir/build/BUILDROOT/foreman-1.0.1-33.13833d4.fc17.noarch/etc/logrotate.d/foreman
install: cannot stat `extras/spec/logrotate': No such file or directory
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.iAfGFP (%install)
    Bad exit status from /var/tmp/rpm-tmp.iAfGFP (%install)