Fixes #35853 - compute_resources_vms_controller_test
Issues:
1) @vm.volumes with array of nils instead of volumes
ComputeResourcesVmsControllerTest#test_0001_should show vm:
ActionView::Template::Error: undefined method `allocation' for nil:NilClass

2) Missing flags => 0 in default options for destroy method, see fog-libvirt PR [0]
ComputeResourcesVmsControllerTest#test_0001_should destroy vm:
NoMethodError: undefined method `zero?' for nil:NilClass

[0] https://github.com/fog/fog-libvirt/pull/102/files